version: '3'

services:

  server:
    build:
        context: "."
    image: galaxy_server:devel
    restart: on-failure
    container_name: galaxy_server_container
    command: make run_service
    env_file: server/environment/server.env
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - 6424:6424

  attack_mission:
    build: .
    image: galaxy_server:devel
    restart: on-failure
    command: make attack_mission
    env_file: server/environment/server.env
    depends_on:
      - server

  farm:
    build: .
    image: galaxy_server:devel
    restart: on-failure
    command: make start_farms
    env_file: server/environment/server.env
    depends_on:
      - server


volumes:
  static_data:
