# Generated by Django 3.2.6 on 2025-05-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('galaxy', models.IntegerField()),
                ('solar_system', models.IntegerField()),
                ('position', models.IntegerField()),
                ('water', models.IntegerField(default=0)),
                ('steel', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('temperature', models.FloatField()),
                ('water_farm_lv', models.IntegerField(default=1)),
                ('gold_mine_lv', models.IntegerField(default=1)),
                ('steel_mine_lv', models.IntegerField(default=1)),
                ('fields_used', models.IntegerField(default=0)),
                ('military_power', models.IntegerField(default=0)),
                ('engine_power', models.IntegerField(default=1)),
                ('shield_power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('offense_power', models.IntegerField()),
                ('shield_power', models.IntegerField()),
                ('cargo_space', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxies', models.ManyToManyField(to='api.Galaxy')),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('galaxy_position', models.IntegerField()),
                ('galaxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.galaxy')),
                ('position_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='api.planet')),
                ('position_10', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='api.planet')),
                ('position_11', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p11', to='api.planet')),
                ('position_12', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p12', to='api.planet')),
                ('position_13', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p13', to='api.planet')),
                ('position_14', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p14', to='api.planet')),
                ('position_15', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p15', to='api.planet')),
                ('position_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='api.planet')),
                ('position_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='api.planet')),
                ('position_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='api.planet')),
                ('position_5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='api.planet')),
                ('position_6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='api.planet')),
                ('position_7', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='api.planet')),
                ('position_8', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='api.planet')),
                ('position_9', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='api.planet')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='fleet',
            field=models.ManyToManyField(to='api.Ship'),
        ),
    ]
