# Generated by Django 3.2.6 on 2025-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('origin_galaxy', models.IntegerField()),
                ('origin_solar_system', models.IntegerField()),
                ('origin_position', models.IntegerField()),
                ('target_galaxy', models.IntegerField()),
                ('target_solar_system', models.IntegerField()),
                ('target_position', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('steel', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('retreat', models.BooleanField(default=False)),
                ('report', models.TextField()),
                ('launch_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('distance', models.IntegerField()),
                ('success', models.BooleanField()),
                ('travel_time', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('fleet', models.ManyToManyField(to='api.Ship')),
            ],
        ),
    ]
