# Generated by Django 3.2.6 on 2025-05-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solarsystem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='gold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='planet',
            name='steel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='planet',
            name='water',
            field=models.FloatField(default=0),
        ),
    ]
