ships = [
  {
    "id": 0,
    "name": "Delta Freighter",
    "description": "A small automated transport ship. Ideal for beginners.",
    "offense": 2,
    "shield": 5,
    "cargo": 100,
    "speed": 10,
    "cost": { "steel": 300, "water": 150, "gold": 60 },
    "build_time": 60,
    "requirements": { "military_power": 1, "shield_power": 1, "engine_power": 2 }
  },
  {
    "id": 1,
    "name": "Vespid Hunter",
    "description": "The first combat ship: light, fast, and effective in surprise attacks.",
    "offense": 12,
    "shield": 8,
    "cargo": 20,
    "speed": 25,
    "cost": { "steel": 600, "water": 240, "gold": 150 },
    "build_time": 90,
    "requirements": { "military_power": 4, "shield_power": 2, "engine_power": 3 }
  },
  {
    "id": 2,
    "name": "Battle Ray",
    "description": "Medium-sized ship equipped with pulse weapons. Well-balanced design.",
    "offense": 25,
    "shield": 20,
    "cargo": 80,
    "speed": 18,
    "cost": { "steel": 1200, "water": 500, "gold": 300 },
    "build_time": 150,
    "requirements": { "military_power": 6, "shield_power": 4, "engine_power": 3 }
  },
  {
    "id": 3,
    "name": "Gamma Hauler",
    "description": "Cargo ship equipped with defensive turrets. Ideal for long-range transport.",
    "offense": 10,
    "shield": 30,
    "cargo": 400,
    "speed": 15,
    "cost": { "steel": 1400, "water": 600, "gold": 350 },
    "build_time": 180,
    "requirements": { "military_power": 3, "shield_power": 6, "engine_power": 5 }
  },
  {
    "id": 4,
    "name": "Vulcan Destroyer",
    "description": "Heavy warship built for massive damage against medium fleets.",
    "offense": 50,
    "shield": 45,
    "cargo": 60,
    "speed": 12,
    "cost": { "steel": 2400, "water": 1000, "gold": 800 },
    "build_time": 300,
    "requirements": { "military_power": 10, "shield_power": 7, "engine_power": 5 }
  },
  {
    "id": 5,
    "name": "Star Falcon",
    "description": "Elite tactical ship with advanced maneuverability.",
    "offense": 40,
    "shield": 25,
    "cargo": 100,
    "speed": 35,
    "cost": { "steel": 2200, "water": 1100, "gold": 900 },
    "build_time": 270,
    "requirements": { "military_power": 9, "shield_power": 5, "engine_power": 8 }
  },
  {
    "id": 6,
    "name": "Leviathan Dreadnought",
    "description": "Colossal warship. A true mobile fortress.",
    "offense": 120,
    "shield": 130,
    "cargo": 300,
    "speed": 8,
    "cost": { "steel": 6000, "water": 2500, "gold": 3000 },
    "build_time": 600,
    "requirements": { "military_power": 15, "shield_power": 15, "engine_power": 6 }
  },
  {
    "id": 7,
    "name": "Phantom Specter",
    "description": "Stealth ship with partial cloaking technology. Specializes in ambush attacks.",
    "offense": 60,
    "shield": 50,
    "cargo": 50,
    "speed": 50,
    "cost": { "steel": 3600, "water": 1800, "gold": 2100 },
    "build_time": 480,
    "requirements": { "military_power": 12, "shield_power": 8, "engine_power": 12 }
  },
  {
    "id": 8,
    "name": "Omega Singularity",
    "description": "Gravity-bending vessel that folds space. Uses antimatter weaponry.",
    "offense": 200,
    "shield": 180,
    "cargo": 500,
    "speed": 60,
    "cost": { "steel": 10000, "water": 5000, "gold": 8000 },
    "build_time": 900,
    "requirements": { "military_power": 20, "shield_power": 15, "engine_power": 15 }
  },
  {
    "id": 9,
    "name": "Quantum Devastator",
    "description": "Built from remnants of forgotten civilizations. Channels black hole energy.",
    "offense": 300,
    "shield": 250,
    "cargo": 100,
    "speed": 40,
    "cost": { "steel": 14000, "water": 7000, "gold": 12000 },
    "build_time": 1200,
    "requirements": { "military_power": 25, "shield_power": 20, "engine_power": 12 }
  }
]
